(defvar python-prettify-symbols-alist
  '(("lambda" . ?λ)
    ("self" . ?自)
    ("yield" . ?⇢)
    ("return" . ?↪)
    ("try" . ?😱) ;; ⚠
    ("except" . ?⛐)
    ("raise" . ?💥)
    ("assert" . ?✓)
    ("<=" . ?≤)
    (">=" . ?≥)
    ("!=" . ?≠)
    ("or" . ?∨)
    ("and" . ?∧)
    ("None" . ?⊥)
    ("in" . ?∈)
    ("set()" . ?∅)
    ("not in" . ?∉)))

(provide 'python-prettify)
